---
- name: configure forticlient repo
  copy:
    src: forticlient.repo
    dest: /etc/yum.repos.d/forticlient.repo
    owner: root
    group: root
    mode: 0644

- name: install forticlient
  package:
    name: "{{ item }}"
    state: present
  loop:
    - forticlient
    - NetworkManager-fortisslvpn
    - NetworkManager-fortisslvpn-gnome

- name: ensure variables to set up is defined
  set_fact:
    vpn_ip_address: "{{ lookup('env','VPN_IP_ADDRESS') }}"
    vpn_username: "{{ lookup('env','USER') }}"
    vpn_cert: "{{ lookup('env','VPN_CERT') }}"
  when: install_forticlient is True

- name: copy azure vpn setting
  template:
    src: "Azure.j2"
    dest: "/etc/NetworkManager/system-connections/Azure"
    owner: root
    group: root
    mode: 0400
    force: True
  when:
    - vpn_cert | length > 0
    - vpn_ip_address | length > 0
    - vpn_username | length > 0
