---
- name: download vagrant
  get_url:
    url: "{{ vagrant_download_url }}"
    dest: "{{ ansible_pkgs_dir }}/{{ vagrant_pkg }}"
    checksum: "sha256:{{ vagrant_checksum }}"
    timeout: 20
    validate_certs: no
  register: _download_vagrant
  until: _download_vagrant is succeeded
  tags: ["vagrant", "download-vagrant"]

- name: install vagrant
  package:
    name: "{{ ansible_pkgs_dir }}/{{ vagrant_pkg }}"
    state: present
  tags: ["vagrant", "install-vagrant"]

- name: install libvirt
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libvirt
    - libvirt-devel
    - qemu
  tags: ["vagrant", "install-libvirt"]

- name: install vagrant libvirt plugin
  shell: "CONFIGURE_ARGS='with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib' vagrant plugin install vagrant-libvirt"
  tags: ["vagrant", "install-libvirt-plugin"]

- name: copy virt-rules
  copy:
    src: virt.rules
    dest: /etc/polkit-1/rules.d/10-virt.rules
    mode: 0644
  tags: ["vagrant", "copy-virt-rules"]

- name: allow user access to libvirt
  user:
    name: "{{ running_user_id }}"
    groups: libvirt
    append: True
  tags: ["vagrant", "allow-libvirt-user"]
