---
- name: configure vscode repo
  copy:
    src: vscode.repo
    dest: /etc/yum.repos.d/vscode.repo
    mode: 0644

- name: install vscode
  become: true
  package:
    name: code
    state: present
