---
- name: configure yarn repo
  copy:
    src: yarn.repo
    dest: /etc/yum.repos.d/yarn.repo
    owner: root
    group: root
    mode: 0644
  tags: ["nodejs", "configure-yarn-repo"]

- name: install nodejs
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - npm
    - yarn
  tags: ["nodejs", "install-nodejs-pkgs"]

- name: create user global npm packages dir
  file:
    path: "{{ running_user_dir }}/.npm-packages"
    state: directory
  tags: ["nodejs", "npm-pkg-dir"]

- name: install npm config file
  copy:
    src: npmrc
    dest: "{{ running_user_dir }}/.npmrc"
    mode: 0644
  tags: ["nodejs", "copy-npm-config"]

- name: install node packages
  npm:
    global: yes
    name: "{{ item }}"
  with_items:
    - tern
    - eslint
    - remark-lint
    - remark-cli
    - remark-preset-lint-recommended
    - stylelint
    - stylelint-config-standard
    - js-yaml
    - jsonlint
    - dockerlint
    - babel-cli
    - babel-preset-es2015
    - gulp
    - tldr
  tags: ["nodejs", "install-node-pkgs"]
