---
- name: configure yarn repo
  copy:
    src: yarn.repo
    dest: /etc/yum.repos.d/yarn.repo
    owner: root
    group: root
    mode: 0644

- name: install nodejs
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - nodejs
    - npm
    - yarn

- name: create user global npm packages dir
  file:
    path: "{{ running_user_dir }}/.npm-packages"
    state: directory

- name: install npm config file
  copy:
    src: npmrc
    dest: "{{ running_user_dir }}/.npmrc"
    mode: 0644

- name: install node packages
  npm:
    global: yes
    name: "{{ item }}"
  loop:
    - tern
    - eslint
    - remark-lint
    - remark-cli
    - remark-preset-lint-recommended
    - stylelint
    - stylelint-config-standard
    - js-yaml
    - jsonlint
    - dockerlint
    - babel-cli
    - babel-preset-es2015
    - gulp
    - tldr
