---
- name: install python packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python-pip
    - python3-pip
    - python-virtualenv
    - python3-invoke

- name: install python2 packages
  pip:
    executable: /usr/bin/pip
    extra_args: "--user"
    name: "legit"
    state: latest

- name: install python3 packages
  pip:
    executable: /usr/bin/pip3
    extra_args: "--user"
    name: "{{ item }}"
    state: latest
  loop:
    - jedi
    - flake8
    - autopep8
    - isort
    - pytest
    - pytest-watch
    - pytest-flake8
    - pytest-isort
    - pytest-hidecaptured
