---
- name: install python packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip
    - python3-pip
    - python-virtualenv
    - python3-invoke
  tags: ["python", "install-python"]

- name: install python2 packages
  pip:
    executable: /usr/bin/pip
    extra_args: "--user"
    name: "legit"
    state: latest
  tags: ["python", "install-pip2-pkgs"]

- name: install python3 packages
  pip:
    executable: /usr/bin/pip3
    extra_args: "--user"
    name: "{{ item }}"
    state: latest
  with_items:
    - jedi
    - flake8
    - autopep8
    - isort
    - pytest
    - pytest-watch
    - pytest-flake8
    - pytest-isort
    - pytest-hidecaptured
  tags: ["python", "install-pip3-pkgs"]
