---
- name: create bin dir
  file:
    path: "{{ running_user_dir }}/bin"
    state: directory

- name: install git commands
  copy:
    src: "{{ item  }}"
    dest: "{{ running_user_dir }}/bin/{{ item }}"
    mode: 0755
  loop:
    - git-alias
    - git-branch-clean-old
    - git-branch-squash
    - git-clear
    - git-fetch-merge-request
    - git-fetch-pull-request
    - git-get
    - git-ignore-io
    - git-line-summary
    - git-log-linear
    - git-log-tree
    - git-mr-squash
    - git-nuke
    - git-patch
    - git-pr-squash
    - git-publish
    - git-push-all
    - git-rename-tag
    - git-undo
    - git-up
    - git-up-changelog
    - git-wtf

- name: copy gitconfig lib
  copy:
    src: gitconfig.lib
    dest: "{{ running_user_dir }}/.gitconfig.lib"
    mode: 0644

- name: ensure gitconfig exists
  copy:
    dest: "{{ running_user_dir }}/.gitconfig"
    content: ""
    force: yes
    mode: 0644

- name: add gitconfig lib include
  blockinfile:
    dest: "{{ running_user_dir }}/.gitconfig"
    block: |
      [include]
        path = ~/.gitconfig.lib
