---
- name: install git
  package:
    name: "git"
    state: present
  tags: ["git", "install-git"]

- name: create bin dir
  file:
    path: "{{ running_user_dir }}/bin"
    state: directory
  tags: ["git", "create-bin-dir"]

- name: install git commands
  copy:
    src: "{{ item  }}"
    dest: "{{ running_user_dir }}/bin/{{ item }}"
    mode: 0755
  with_items:
    - git-alias
    - git-up-changelog
    - git-fetch-merge-request
    - git-fetch-pull-request
    - git-branch-clean-old
    - git-branch-squash
    - git-mr-squash
    - git-pr-squash
    - git-ignore-io
    - git-line-summary
    - git-log-linear
    - git-log-tree
    - git-nuke
    - git-patch
    - git-push-all
    - git-publish
    - git-rename-tag
    - git-undo
    - git-up
    - git-get
    - git-clear
    - git-wtf
  tags: ["git", "install-git-cmd"]

- name: copy gitconfig lib
  copy:
    src: gitconfig.lib
    dest: "{{ running_user_dir }}/.gitconfig.lib"
    mode: 0644
  tags: ["git", "copy-gitconfig"]

- name: ensure gitconfig exists
  copy:
    dest: "{{ running_user_dir }}/.gitconfig"
    content: ""
    force: no
    mode: 0644
  tags: ["git", "valid-gitconfig"]

- name: add gitconfig lib include
  blockinfile:
    dest: "{{ running_user_dir }}/.gitconfig"
    block: |
      [include]
        path = ~/.gitconfig.lib
  tags: ["git", "gitconfig-include"]
