---
- name: configure fortinet repo
  copy:
    src: fortinet.repo
    dest: /etc/yum.repos.d/fortinet.repo
    owner: root
    group: root
    mode: 0644
  tags: ["fortinet", "configure-fortinet-repo"]

- name: install fortinet
  package:
    name: "fortinet"
    state: present
  tags: ["fortinet", "install-fortinet"]

- name: ensure variables to set up is defined
  set_fact:
    vpn_ip_address: "{{ lookup('env','VPN_IP_ADDRESS') }}"
    vpn_username: "{{ lookup('env','USER') }}"
    vpn_cert: "{{ lookup('env','VPN_CERT') }}"
  tags: ["fortinet", "copy-azure-templete"]

- name: copy azure vpn setting
  template:
    src: "Azure.j2"
    dest: "/etc/NetworkManager/system-connections/Azure"
    owner: root
    group: root
    mode: 0400
    force: True
  when:
    - vpn_cert | length > 0
    - vpn_ip_address | length > 0
    - vpn_username | length > 0
  tags: ["fortinet", "copy-azure-templete"]
