---
- name: configure kuberentes repo
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0644
    force: True

- name: install kubectl tool
  become: true
  package:
    name: kubectl
    state: present

- name: clone kubens/kubectx repository
  git:
    repo: https://github.com/ahmetb/kubectx.git
    dest: "{{ ansible_pkgs_dir }}/kubectx"
    clone: True

- name: install kubens/kubectx tools
  copy:
    src: "{{ ansible_pkgs_dir }}/kubectx/{{ item  }}"
    dest: "{{ running_user_dir }}/bin/{{ item }}"
    mode: 0755
  loop:
    - kubectx
    - kubens

- name: clone kubedecode repository
  git:
    repo: https://github.com/mveritym/kubedecode.git
    dest: "{{ ansible_pkgs_dir }}/kubedecode"
    clone: True

- name: install kubedecode tool
  copy:
    src: "{{ ansible_pkgs_dir }}/kubedecode/bin/kubedecode"
    dest: "{{ running_user_dir }}/bin/kubedecode"
    mode: 0755
