#!/bin/bash

set -e

cd "$(dirname "$0")/.."

if [[ ! $(rpm -aq | grep ansible) ]] || [[ ! $(rpm -aq | grep python3-devel) ]]; then
  echo -n "installing necessary packages to initialize the bootstrap"
  sudo dnf install ansible python3-devel -y
  pip install pipenv --user
fi

if [ ! -f "Pipfile.lock" ]; then
  pipenv install --dev
fi

pipenv shell
