#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

python_version=system

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

if [ -f ".python-version" ] && [ -z "$(pyenv version 2>/dev/null)" ]; then
    python_version="$(cat .python-version)"
    echo "==> Installing Python ${python_version}..."
    pyenv install --skip-existing
    echo "==> Activating Python ${python_version}..."
    pyenv local "$python_version"
fi

if [ -f "requirements.txt" ]; then
   echo "==> Installing pip dependencies..."
   if [ ! -z "$python_version" ]; then
       pip install -U -r requirements.txt
   else
       pip install --user -U -r requirements.txt
   fi
fi

if [ -f "dev_requirements.txt" ]; then
   echo "==> Installing pip development dependencies..."
   if [ ! -z "$python_version" ]; then
       pip install -U -r dev_requirements.txt
   else
       pip install --user -U -r dev_requirements.txt
   fi
fi
