---
- connection: local
  hosts: 127.0.0.1
  become: True
  vars_files:
    - ../vars/main.yml

  roles:
    - pre
    - git
    - cli_tools
    - zsh
    - nodejs
    - python
    - ruby
    - vscode
    - docker
    - dropbox
    - vagrant
    - graphics
    - chrome
    - forticlient
    - terraform
    - k8s-tools
    - slack
    - atom
    - virtualbox
