---
- connection: local
  hosts: 127.0.0.1
  become: True
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    running_user_id: "{{ ansible_user_id }}"
    running_user_dir: "{{ ansible_user_dir }}"
    ansible_pkgs_dir: "{{ running_user_dir }}/.tmp/pkgs"

  pre_tasks:
   - name: create temporary packages dir
     file:
       path: "{{ ansible_pkgs_dir }}"
       state: directory

  post_tasks:
   - name: delete temporary packages dir
     file:
       path: "{{ ansible_pkgs_dir }}"
       state: absent

  roles:
    - bootstrap
    - chrome
    - cli_tools
    - docker
    - dropbox
    - file-agent
    - forticlient
    - k8s-tools
    - nodejs
    - python
    - ruby
    - setup-git
    - terraform
    - vagrant
    - virtualbox
    - vscode
    - zsh
