---
- name: install cli packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - awscli
    - caddy
    - openssh
    - tree
    - nmap
    - telnet
    - tcpdump
    - traceroute
    - mtr
    - nc
    - iftop
    - trafshow
    - ncdu
    - htop
    - screen
    - tmux
    - siege
    - ctags
    - unrar
    - youtube-dl
    - the_silver_searcher
    - Zim
    - terminator
  tags: ["cli_tools"]

- name: install root editorconfig file
  copy:
    src: editorconfig
    dest: "{{ running_user_dir }}/.editorconfig"
    mode: 0644
  tags: ["cli_tools"]
